name: Build KeySwipe11

on:
  workflow_dispatch:
    inputs:
      make_target:
        description: "make target to run"
        default: "package"
        required: false
        type: choice
        options:
          - package
          - all
          - debug
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew update
          brew install ldid make dpkg gnu-sed

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos "$HOME/theos"
          echo "THEOS=$HOME/theos" >> "$GITHUB_ENV"

      - name: Provide iOS SDKs for Theos
        run: |
          git clone https://github.com/theos/sdks.git "$HOME/theos/sdks"

      - name: Build tweak
        env:
          THEOS: ${{ env.THEOS }}
        run: |
          make clean
          if [ -n "${{ github.event.inputs.make_target }}" ]; then
            make ${{ github.event.inputs.make_target }}
          else
            make package
          fi

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: keyswipe11-deb
          path: packages/*.deb
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: macos-13
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: keyswipe11-deb
          path: dist

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.deb
